apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-data-deployment
  labels:
    app: mongo-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-data
  template:
    metadata:
      labels:
        app: mongo-data
    spec:
      containers:
      - name: mongo-data
        image: andonisalcedo/mongo-data:1.0
        ports:
        - containerPort: 8080
      initContainers:
      - name: health-check
        image: curlimages/curl
        command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' http://config-server-service.default.svc.cluster.local:8080/actuator/health | grep -q 200; do sleep 1; done"]
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-data-service
spec:
  selector:
    app: mongo-data
  ports:
  - port: 8080