apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-service-deployment
  labels:
    app: process-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-service
  template:
    metadata:
      labels:
        app: process-service
    spec:
      containers:
      - name: process-service
        image: andonisalcedo/process-service:1.0
        ports:
        - containerPort: 8080
      initContainers:
      - name: health-check
        image: curlimages/curl
        command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' http://config-server-service.default.svc.cluster.local:8080/actuator/health | grep -q 200; do sleep 1; done"]
---
kind: Service
apiVersion: v1
metadata:
  name: process-service-service
spec:
  selector:
    app: process-service
  ports:
  - port: 8080