apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-integrity-cronjob
  labels:
    app: data-integrity
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-integrity
            image: andonisalcedo/data-integrity:1.0
            envFrom:
            - configMapRef:
                name: config-server-url
            ports:
              - containerPort: 8080
          restartPolicy: Never
