apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: andonisalcedo/auth-service:1.0
        ports:
        - containerPort: 8080
      initContainers:
          - name: health-check
            image: curlimages/curl
            command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' http://config-server-service.default.svc.cluster.local:8080/actuator/health | grep -q 200; do sleep 1; done"]
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080