apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-ssd
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-ssd
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/pv2"
