apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # "root" en base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_USER: cm9vdA==  # "root" en base64
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" en base64
  MYSQL_DATABASE: ZGI=  # "db" en base64