apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-data-deployment
  labels:
    app: sql-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-data
  template:
    metadata:
      labels:
        app: sql-data
    spec:
      containers:
      - name: watcher
        image: andonisalcedo/sql-data:1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sql-data-service
spec:
  selector:
    app: sql-data
  ports:
  - port: 8080