apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api-deployment
  labels:
    app: consumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-api
  template:
    metadata:
      labels:
        app: consumer-api
    spec:
      initContainers:
        - name: health-check
          image: curlimages/curl
          command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' ${SPRING_CLOUD_CONFIG_URI}/actuator/health | grep -q 200; do sleep 1; done"]
          env:
          - name: SPRING_CLOUD_CONFIG_URI
            valueFrom:
              configMapKeyRef:
                name: config-server-url
                key: SPRING_CLOUD_CONFIG_URI
      containers:
      - name: consumer-api
        image: andonisalcedo/consumer-api:1.0
        envFrom:
        - configMapRef:
            name: config-server-url
        ports:
          - containerPort: 8080
---      
kind: Service
apiVersion: v1
metadata:
  name: consumer-api-service
spec:
  selector:
    app: consumer-api
  ports:
  - port: 8080