apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: health-check
          image: curlimages/curl
          command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' ${SPRING_CLOUD_CONFIG_URI}/actuator/health | grep -q 200; do sleep 1; done"]
          env:
          - name: SPRING_CLOUD_CONFIG_URI
            valueFrom:
              configMapKeyRef:
                name: config-server-url
                key: SPRING_CLOUD_CONFIG_URI
      containers:
      - name: worker
        image: andonisalcedo/worker:1.0
        envFrom:
        - configMapRef:
            name: config-server-url
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
---      
kind: Service
apiVersion: v1
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  ports:
  - port: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50