apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api-deployment
  labels:
    app: validator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-api
  template:
    metadata:
      labels:
        app: validator-api
    spec:
      containers:
      - name: validator-api
        image: andonisalcedo/validator-api:1.0
        ports:
        - containerPort: 8080
      initContainers:
          - name: health-check
            image: curlimages/curl
            command: ["sh", "-c", "until curl -s -o /dev/null -w '%{http_code}' http://config-server-service.default.svc.cluster.local:8080/actuator/health | grep -q 200; do sleep 1; done"]
---
kind: Service
apiVersion: v1
metadata:
  name: validator-api-service
spec:
  selector:
    app: validator-api
  ports:
  - port: 8080